# Generated by Django 5.1.2 on 2024-10-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
